export type ServiceCatalogItem = {
  title: string;
  description: string;
  image: string;
  slug?: string;
};

export const serviceCatalogItems: ServiceCatalogItem[] = [
  { title: "AERIAL", description: "Graceful aerial dancers mesmerize with breathtaking, gravity-defying performances in the air.", image: "/images/services/aerial.webp" },
  { title: "AUCTIONEERS", description: "Engaging auctioneers captivate crowds with charisma, commanding bids with flair.", image: "/images/services/auctioneer.webp" },
  { title: "BAGPIPES", description: "Captivating audiences with haunting bagpipe melodies, a true musical maestro.", image: "/images/services/bagpipes.webp" },
  { title: "BALLOON ART", description: "Balloon artists sculpt whimsical wonders, inflating joy at every event.", image: "/images/services/balloon.webp" },
  { title: "BELLY DANCERS", description: "Belly dancers mesmerize with fluid movements and vibrant, rhythmic performances.", image: "/images/services/belly.webp" },
  { title: "BONGO PLAYERS", description: "Bongo players infuse rhythm, energy and soul into every beat.", image: "/images/services/bongo.webp" },
  { title: "BRASS BANDS", description: "Energetic brass ensembles ignite celebrations with irresistible melodies and rhythm.", image: "/images/services/brass.webp" },
  { title: "BURLESQUE", description: "Sensual, charismatic entertainers who blend dance, humor and seduction seamlessly.", image: "/images/services/burlesque.webp" },
  { title: "CIRCUS ACTS", description: "Captivating circus acts astonish with acrobatics, magic and daring feats.", image: "/images/services/circus.webp", slug: "circus-performers" },
  { title: "COMEDIANS", description: "Masters of humor, weaving laughter into life's tapestry effortlessly.", image: "/images/services/comedy.webp" },
  { title: "DJs", description: "Master of beats, turning parties into unforgettable dance extravaganzas.", image: "/images/services/dj.webp", slug: "djs" },
  { title: "DRUMMERS", description: "Rhythmic virtuosos, drummers beat hearts to the music's pulse.", image: "/images/services/drummer.webp" },
  { title: "FIRE DANCERS", description: "Fire dancers mesmerize with flames, rhythm and breathtaking artistry in motion.", image: "/images/services/fire.webp" },
  { title: "GRAZING TABLES", description: "Abundant spreads of delectable delights, a feast for all senses.", image: "/images/services/grazing.webp" },
  { title: "GUITARISTS", description: "Versatile guitarists on acoustic and electric, creating melodic magic.", image: "/images/services/guitar.webp" },
  { title: "GYMNASTS", description: "Amaze guests with incredible flexibility and graceful athletic movement.", image: "/images/services/gymnast.webp" },
  { title: "HARPISTS", description: "Elegant melodies flow from graceful fingers, enchanting every heart.", image: "/images/services/harp.webp" },
  { title: "HORN PLAYERS", description: "Masterful horn players conjure melodies that stir the soul's depths.", image: "/images/services/horn.webp" },
  { title: "HOSTS & HOSTESSES", description: "Charming event hosts and hostesses elevate any gathering with charisma.", image: "/images/services/host.webp" },
  { title: "HYPE DANCERS", description: "Energetic dancers ignite the crowd with electrifying, high-energy performances.", image: "/images/services/dancer.webp", slug: "dancers" },
  { title: "ILLUSIONISTS & MAGIC", description: "Illusionists craft enchanting worlds where magic defies ordinary reality.", image: "/images/services/magic.webp", slug: "magicians" },
  { title: "LED & PLAIN DANCEFLOORS", description: "Vibrant LED and elegant plain dance floors illuminate any event.", image: "/images/services/dancefloor.webp" },
  { title: "LED LETTERS & NUMBERS", description: "LED letters and numbers illuminate messages with eye-catching brilliance.", image: "/images/services/led.webp" },
  { title: "LED MUSICIANS", description: "Musicians electrify the stage with mesmerizing performances using LED instruments.", image: "/images/services/led-music.webp" },
  { title: "LED WINGS", description: "Illuminated wings mesmerize, casting a vibrant aura of light and magic.", image: "/images/services/wings.webp" },
  { title: "LIGHTING", description: "Illuminating spaces, setting moods and creating ambiance through designed lighting.", image: "/images/services/lighting.webp" },
  { title: "MAGIC MIRROR", description: "An enchanting mirror that captures moments with a touch of photographic wizardry.", image: "/images/services/magic-mirror.webp" },
  { title: "MAKE UP & TATTOOS", description: "Party makeup and tattoo artists transform faces and bodies into masterpieces.", image: "/images/services/make-up.webp" },
  { title: "MARQUEE HIRE", description: "Elevate your event with exquisite, spacious and versatile marquee hire.", image: "/images/services/marquee.webp" },
  { title: "MASTER OF CEREMONIES", description: "Charismatic hosts who orchestrate events with poise and enthusiasm.", image: "/images/services/mc.webp" },
  { title: "MIRROR BALLERINAS", description: "Graceful ballerinas enchant audiences with mirrored suits and timeless artistry.", image: "/images/services/mirror-bal.webp" },
  { title: "MIRROR MEN", description: "Mirror Men mesmerize with reflective artistry and shimmering illusions.", image: "/images/services/mirror-men.webp" },
  { title: "OOMPAH BANDS", description: "Lively festive music that makes celebrations unforgettable.", image: "/images/services/oompah.webp" },
  { title: "PHOTO BOOTHS", description: "Capture joyous moments with interactive, fun-filled photo booth experiences.", image: "/images/services/photobooth.webp" },
  { title: "PIANISTS & KEYS PLAYERS", description: "Pianists and keys players harmonize melodies with exquisite precision.", image: "/images/services/piano.webp" },
  { title: "PODIUM DANCERS", description: "Podium dancers ignite stages with electrifying moves and presence.", image: "/images/services/podium.webp" },
  { title: "ROAMING BANDS", description: "Roaming bands infuse events with dynamic live musical energy and interaction.", image: "/images/services/roaming.webp" },
  { title: "ROAMING PERCUSSION", description: "Dynamic mobile percussion that ignites vibrant rhythms across your event.", image: "/images/services/roaming.webp" },
  { title: "ROBOTS", description: "Futuristic robots electrify dance floors and create unforgettable moments.", image: "/images/services/robot.webp" },
  { title: "ROLLER GIRLS & BOYS", description: "Roller performers skate, groove and celebrate in style.", image: "/images/services/skates.webp" },
  { title: "SAXOPHONISTS", description: "Expressive musicians crafting soulful melodies with versatile saxophone performances.", image: "/images/services/sax.webp" },
  { title: "SELFIE PODS", description: "Instant fun, memorable photos and engaging entertainment options.", image: "/images/services/selfie.webp" },
  { title: "SHOW GIRLS", description: "Dazzling showgirls captivate with glamour, feathers and sensational presence.", image: "/images/services/showgirl.webp" },
  { title: "SINGERS", description: "Vocalists harmonize emotions through melodies, connecting hearts with stories.", image: "/images/services/singer.webp", slug: "singers" },
  { title: "SOUND HIRE", description: "Quality audio equipment for events that resonate with excellence.", image: "/images/services/sound.webp" },
  { title: "STILTS", description: "Graceful stilt artists elevate events with gravity-defying performances.", image: "/images/services/stilts.webp" },
  { title: "SWEET CARTS", description: "Delight your guests with customizable party sweet carts.", image: "/images/services/cart.webp" },
  { title: "VIOLINISTS", description: "Versatile virtuosos creating enchanting melodies on acoustic and electric violin.", image: "/images/services/violin.webp" },
  { title: "LIVE MUSICIANS", description: "Curated live musicians for premium event atmosphere and flow.", image: "/images/services/band.webp", slug: "musicians" },
];
